#!/usr/bin/env bash
set -euo pipefail

if ! command -v supabase >/dev/null 2>&1; then
  echo "Supabase CLI is required." >&2
  exit 1
fi

# Export the local Supabase credentials generated by the CLI.
eval "$(supabase status -o env)"
